@extends('reports.layout')
@section('title', 'Staff Performance Report')
@section('report_name', 'Staff Performance Report')
@section('content')
    <div class="summary-box">
        <p>This report tracks total orders handled and revenue generated by each staff member.</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 10%;">#</th>
                <th style="width: 40%;">Staff Name / Email</th>
                <th style="width: 25%;" class="text-right">Orders Handled</th>
                <th style="width: 25%;" class="text-right">Total Revenue Generated</th>
            </tr>
        </thead>
        <tbody>
            @php $totalOrders = 0; $totalSales = 0; @endphp
            @foreach($staffData as $staff)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $staff->name }} ({{ $staff->email }})</td>
                    <td class="text-right">{{ number_format($staff->orders_count) }}</td>
                    <td class="text-right">৳{{ number_format($staff->orders_sum_total_amount, 2) }}</td>
                </tr>
                @php 
                    $totalOrders += $staff->orders_count;
                    $totalSales += $staff->orders_sum_total_amount;
                @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr class="bg-gray-100 font-bold">
                <td colspan="2">TOTAL</td>
                <td class="text-right">{{ number_format($totalOrders) }}</td>
                <td class="text-right">৳{{ number_format($totalSales, 2) }}</td>
            </tr>
        </tfoot>
    </table>
@endsection
